<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    //Generated by fakenamegenerator to have completed made-up people with name and belgian adddress
    public function run(): void
    {
        DB::table('users')->insert([
            'id' => 3,
            'name' => 'client1',
            'email' => 'client1@rokuban.be',
            'email_verified_at' => \Carbon\Carbon::now(),
            'password' => Hash::make('mdb4i58d48d3'), //randomly generate using an online generator
            'first_name' => 'Alain',
            'last_name' => 'Dubois',
            'address_line_1' => 'Rue de Baras 31',
            'address_line_2' => null,
            'postal_code' => '7070',
            'city' => 'Thieu',
            'role_id' => 2,
            'isActive' => 1,
            'remember_token' => null,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('users')->insert([
            'id' => 4,
            'name' => 'client2',
            'email' => 'client2@rokuban.be',
            'email_verified_at' => \Carbon\Carbon::now(),
            'password'=> Hash::make('wap3265pf5y6'), //randomly generate using an online generator
            'first_name' => 'Gilbert',
            'last_name' => 'Marois',
            'address_line_1' => 'Rue de Piétrain 275',
            'address_line_2' => null,
            'postal_code' => '6851',
            'city' => 'Nollevaux',
            'role_id' => 2,
            'isActive' => 1,
            'remember_token' => null,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('users')->insert([
            'id' => 5,
            'name' => 'client3',
            'email' => 'client3@rokuban.be',
            'email_verified_at' => \Carbon\Carbon::now(),
            'password'=> Hash::make('34m8v9makg82'), //randomly generate using an online generator
            'first_name' => 'Zoé',
            'last_name' => 'Marcoux',
            'address_line_1' => 'Rue Grande 287',
            'address_line_2' => null,
            'postal_code' => '9800',
            'city' => 'Bachte-Maria-Leerne',
            'role_id' => 2,
            'isActive' => 1,
            'remember_token' => null,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('users')->insert([
            'id' => 6,
            'name' => 'client4',
            'email' => 'client4@rokuban.be',
            'email_verified_at' => \Carbon\Carbon::now(),
            'password'=> Hash::make('sma77z9a47s5'), //randomly generate using an online generator
            'first_name' => 'Natalie',
            'last_name' => 'Desforges',
            'address_line_1' => 'Witbakkerstraat 125',
            'address_line_2' => null,
            'postal_code' => '8600',
            'city' => 'Sint-Jacobs-Kapelle',
            'role_id' => 2,
            'isActive' => 1,
            'remember_token' => null,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('users')->insert([
            'id' => 7,
            'name' => 'client5',
            'email' => 'client5@rokuban.be',
            'email_verified_at' => \Carbon\Carbon::now(),
            'password'=> Hash::make('qj372f3ckm74'), //randomly generate using an online generator
            'first_name' => 'Michel',
            'last_name' => 'Blondieau',
            'address_line_1' => 'Rue Fouramont 384',
            'address_line_2' => null,
            'postal_code' => '7100',
            'city' => 'Haine-Saint-Pierre',
            'role_id' => 2,
            'isActive' => 0,
            'remember_token' => null,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);
    }
}
