<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FigureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('figures')->insert([
            'id' => 1,
            'name' => 'Altria Pendragon - Saber - Triumphant Excalibur',
            'description' => 'Figurine de Saber, Altria Pendragon, en version Triumphant Excalibur d\' une taille de 25cm (1/7è) produite par Good Smile Company par le sculpteur Kawahara Takayuki en PVC et qui fait partie de la série animée et de jeux-vidéos Fate Stay Night. Cette figurine est prépeinte.',
            'image_path' => null,
            'price' => 139.99,
            'tva_id' => 1,
            'brand_id' => 1,
            'collection' => 'Saber Collection',
            'character_name' => 'Saber',
            'series_title' => 'Fate Stay Night',
            'sculptor_name' => 'Kawahara Takayuki',
            'material' => 'PVC',
            'height' => '25 cm',
            'scale_id' => 1,
            'release_date' => '20/06/2018',
            'stock_qty' => 25,
            'reference' => 'FSN000001GSC',
            'ean' => '1234567899875',
            'state' => 'Neuve',
            'category_id' => 1,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 2,
            'name' => 'Altria Pendragon - Saber - Motored Cuirassier',
            'description' => 'Figurine de Saber, Altria Pendragon, en version Motored Cuirassier d\' une taille de 25cm (1/7è) produite par Good Smile Company par le sculpteur Kawahara Takayuki en PVC et qui fait partie de la série animée et de jeux-vidéos Fate Zero. Cette figurine est prépeinte.',
            'image_path' => null, 
            'price' => 199.99,
            'tva_id' => 1,
            'brand_id' => 1,
            'collection' => 'Aucune',
            'character_name' => 'Saber',
            'series_title' => 'Fate Zero',
            'sculptor_name' => 'Kawahara Takayuki',
            'material' => 'PVC',
            'height' => '25 cm',
            'scale_id' => 1,
            'release_date' => '22/05/2017',
            'stock_qty' => 30,
            'reference' => 'FZ00000075GSC',
            'ean' => '1234567899876',
            'state' => 'Neuve',
            'category_id' => 1,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 3,
            'name' => 'Dark Angel Olivia - White ver.',
            'description' => 'Figurine de Dark Angel Olivia, tenue blanche, d\' une taille de 29cm (1/7è) produite par Kotobukiya et designée par le sculpteur Matsumuto Kouei en PVC + ABS et qui fait partie du jeu-vidéo Shingeki No Bahamut. Cette figurine est prépeinte.',
            'image_path' => null, 
            'price' => 149.99,
            'tva_id' => 1,
            'brand_id' => 2,
            'collection' => 'SNB',
            'character_name' => 'DA Olivia',
            'series_title' => 'Shingeki no Bahamut',
            'sculptor_name' => 'Matsumuto Kouei',
            'material' => 'PVC, ABS',
            'height' => '29 cm',
            'scale_id' => 1,
            'release_date' => '15/12/2021',
            'stock_qty' => 12,
            'reference' => 'SNB0321511KTB',
            'ean' => '1234567899870',
            'state' => 'Neuve',
            'category_id' => 1,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 4,
            'name' => 'Strelitzia - Moderoid',
            'description' => 'Figurine du robot Strelitzia d\' une taille de 18cm produite par Good Smile Company par le sculpteur Sakanoryo en ABS + PC et qui fait partie de la série animée Darling in the franxx. Cette figurine est prépeinte mais à assembler soit-même.',
            'image_path' => null, 
            'price' => 49.99,
            'tva_id' => 1,
            'brand_id' => 1,
            'collection' => 'Moderoid',
            'character_name' => 'Strelitzia',
            'series_title' => 'Darling in the FranXX',
            'sculptor_name' => 'Sakanoryo',
            'material' => 'ABS, PC',
            'height' => '18 cm',
            'scale_id' => 4,
            'release_date' => '08/02/2023',
            'stock_qty' => 7,
            'reference' => 'STZ250504GMSC',
            'ean' => '1234567899814',
            'state' => 'Neuve',
            'category_id' => 4,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 5,
            'name' => 'Hibino Kafka - Break Time',
            'description' => 'Figurine de Kafka Hibino, en version Break Time, d\' une taille de 8cm produite par SEGA en PVC et ABS et qui fait partie de la série animée Monster 8. Cette figurine est prépeinte.',
            'image_path' => null, 
            'price' => 39.49,
            'tva_id' => 1,
            'brand_id' => 4,
            'collection' => 'Chokonose',
            'character_name' => 'Kafka Hibino',
            'series_title' => 'Fate Stay Night',
            'sculptor_name' => 'Non-indiqué',
            'material' => 'PVC, ABS',
            'height' => '8 cm',
            'scale_id' => 4,
            'release_date' => '20/12/2024',
            'stock_qty' => 150,
            'reference' => 'SEGA050504HBN',
            'ean' => '1234567899827',
            'state' => 'Neuve',
            'category_id' => 3,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 6,
            'name' => 'Ayase Momo - Shifuku Ver.',
            'description' => 'Figurine de Momo Ayase, en version Shifuku, d\' une taille de 6 cm produite par SEGA en PVC et qui fait partie de la série animée Dandadan. Cette figurine est prépeinte.',
            'image_path' => null, 
            'price' => 49.49,
            'tva_id' => 1,
            'brand_id' => 4,
            'collection' => 'Luminasta',
            'character_name' => 'Momo Ayase',
            'series_title' => 'DaDaDan',
            'sculptor_name' => 'Non-indiqué',
            'material' => 'PVC',
            'height' => '6 cm',
            'scale_id' => 4,
            'release_date' => '20/12/2024',
            'stock_qty' => 17,
            'reference' => 'FSN000001GSC',
            'ean' => '1234567899875',
            'state' => 'Neuve',
            'category_id' => 4,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 7,
            'name' => 'Haruno Sakura - Shippuden - Funranguia Trading Figure',
            'description' => 'Figurine de Sakura Haruno, mini-figurine a collectioné produite par Bandai en PVC et qui fait partie de la série animée Naruto Shippuden. Cette figurine est prépeinte.',
            'image_path' => null, 
            'price' => 19.99,
            'tva_id' => 1,
            'brand_id' => 3,
            'collection' => 'Funranguia',
            'character_name' => 'Sakura Haruno',
            'series_title' => 'Naruto Shippuden',
            'sculptor_name' => 'Non-indiqué',
            'material' => 'PVC',
            'height' => '4 cm',
            'scale_id' => 1,
            'release_date' => '04/05/2024',
            'stock_qty' => 8,
            'reference' => 'NRT123456SGA',
            'ean' => '1234567899123',
            'state' => 'Neuve',
            'category_id' => 3,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 8,
            'name' => 'GAT-X105+AQM/E-YM1 Perfect Strike Gundam - PG ',
            'description' => 'Model kit de GAT-X105+AQM/E-YM1, en version Perfect Strike, d\' une taille de 50cm (1/60è) produite par Bandai en PVC et qui fait partie de la série animée Mobile Suit Gundam Seed. Cette figurine est prépeinte et a montée soit-même.',
            'image_path' => null, 
            'price' => 299.99,
            'tva_id' => 1,
            'brand_id' => 3,
            'collection' => 'PG',
            'character_name' => 'GAT-X105',
            'series_title' => 'Gundam SEED',
            'sculptor_name' => 'Non-indiqué',
            'material' => 'PVC',
            'height' => '50 cm',
            'scale_id' => 5,
            'release_date' => '20/06/2018',
            'stock_qty' => 5,
            'reference' => 'GD0004500SEED',
            'ean' => '1234567899911',
            'state' => 'Neuve',
            'category_id' => 4,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 9,
            'name' => ' 2B - YoRHa No.2 Type B -  Deluxe ed.',
            'description' => 'Figurine de 2B, en édition deluxe, d\' une taille de 20cm (1/7è) produite par Aniplex par le sculpteur Inaba en PVC + ABS et qui fait partie de la série animée et de jeux-vidéos Nier:Automata. Cette figurine est prépeinte.',
            'image_path' => null, 
            'price' => 329.99,
            'tva_id' => 1,
            'brand_id' => 5,
            'collection' => 'YoRHa',
            'character_name' => '2B',
            'series_title' => 'Nier Automata',
            'sculptor_name' => 'Inaba',
            'material' => 'PVC, ABS',
            'height' => '20 cm',
            'scale_id' => 1,
            'release_date' => '20/09/2024',
            'stock_qty' => 31,
            'reference' => 'YRA009009ANI',
            'ean' => '1234567891111',
            'state' => 'Neuve',
            'category_id' => 1,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        DB::table('figures')->insert([
            'id' => 10,
            'name' => 'Kanjiro Mitsuri - WING',
            'description' => 'Figurine de Mitsuri Kanjiro, édition WING, d\' une taille de 19cm (1/7è) produite par Aniplex par le sculpteur Ene en PVC + ABS et qui fait partie de la série animée Demon Slayer. Cette figurine est prépeinte.',
            'image_path' => null, 
            'price' => 219.99,
            'tva_id' => 1,
            'brand_id' => 5,
            'collection' => 'WING',
            'character_name' => 'Mitsuri Kanjiro',
            'series_title' => 'Demon Slayer',
            'sculptor_name' => 'Ene',
            'material' => 'PVC, ABS',
            'height' => '19 cm',
            'scale_id' => 1,
            'release_date' => '08/11/2024',
            'stock_qty' => 2,
            'reference' => 'PLE11W4514ANI',
            'ean' => '1237567897123',
            'state' => 'Neuve',
            'category_id' => 1,
            'isVisible' => 1,
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ]);

        /**
          *  DB::table('figures')->insert([
          *  'id' => 1,
          *  'name' => '',
          *  'description' => '.',
          *  'image_path' => '',
          *  'price' => 100.0,
          *  'tva_id' => 1,
          *  'brand_id' =>1,
          *  'collection' => '',
          *  'character_name' => '',
          *  'series_title' => '',
          *  'sculptor_name' => '',
          *  'material' => '',
          *  'height' => '',
          *  'scale_id' => 1,
          *  'release_date' => '',
          *  'stock_qty' => 5,
          *  'reference' => '',
          *  'ean' => '',
          *  'state' => '',
          *  'category_id' => 1,
          *  'isVisible' => 1,
          *  'created_at' => \Carbon\Carbon::now(),
          *  'updated_at' => \Carbon\Carbon::now(),
        * ]); 
        */

    }
}
